version: '3'

services:
  # MySQL service
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: jooq_test
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"

  # Spring Boot application service
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/jooq_test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_DATASOURCE_NAME: jooq_test
